[custom]

;ruleset=🛑 全球拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/BanEasyList.list
;ruleset=🛑 全球拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/BanEasyListChina.list
ruleset=🛑 全球拦截,GEOSITE,category-ads-all
;ruleset=☁️ 全球直连,[]GEOIP,LAN
ruleset=☁️ 全球直连,[]GEOIP,CN,no-resolve
ruleset=☁️ 全球直连,[]GEOSITE,CN
ruleset=🦢 漏网之鱼,[]FINAL

custom_proxy_group=⚡️ 节点选择`select`.*`http://www.gstatic.com/generate_204`600,3000,100
custom_proxy_group=✨ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`600,3000,100
custom_proxy_group=⚖️ 故障转移`fallback`[]⚡️ 节点选择`[]✨ 自动选择`http://www.gstatic.com/generate_204`600,3000,100
custom_proxy_group=☁️ 全球直连`select`[]DIRECT`[]⚡️ 节点选择
custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🦢 漏网之鱼`select`[]⚖️ 故障转移`[]☁️ 全球直连

enable_rule_generator=true
overwrite_original_rules=true
clash_rule_base=https://raw.githubusercontent.com/Filterrr/Clashruleset/main/config/clashdns.yml
